#!/usr/bin/env bash

# Set the display layout
xrandr \
  --output DP-1-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
  --output DP-1-3 --mode 1920x1080 --pos 1920x0 --rotate normal \
  --output eDP-1 --mode 2560x1600 --pos 960x1080 --rotate normal
