#!/usr/bin/env bash

KEY_FILE="$HOME/.config/i3/rofi/keybinds.txt"
THEME="$HOME/.config/i3/rofi/keybinds.rasi"

awk -F ";" '
BEGIN {
    # First pass: determine column widths
    while ((getline line < ARGV[1]) > 0) {
        if (line ~ /^==/) continue;
        split(line, f, ";");
        if (length(f[1]) > max_key) max_key = length(f[1]);
        if (length(f[2]) > max_desc) max_desc = length(f[2]);
    }
    close(ARGV[1]);
    # Small padding
    max_key += 2;
    max_desc += 3;
}

# Pass 2: print formatted output
(/^==/) {
    # Header line → styled with Pango
    printf "<span foreground=\"#268bd2\" weight=\"bold\">%s</span>\n", $0;
    next;
}

NF==3 {
    # Align dynamically
    printf "%-" max_key "s %-" max_desc "s %s\n", $1, $2, $3;
}
' "$KEY_FILE" |
rofi -dmenu \
    -p "Keybindings" \
    -theme "$THEME" \
    -i \
    -markup-rows \
    -no-show-icons

