export DISABLE_GIT_WORKTREE_EDITOR=1
export GIT_DEV_DIR="${GIT_DEV_DIR:-$HOME/projects}"

export PROFILE_CACHE_DIR="${PROFILE_CACHE_DIR:-$HOME/.cache}"
export PYTHON_VENV_DIR="${PYTHON_VENV_DIR:-$HOME/.venv}"
export TMUX_PLUGIN_DIR="${TMUX_PLUGIN_DIR:-$HOME/.tmux/plugins}"
export ZELLIJ_CONFIG_DIR="${ZELLIJ_CONFIG_DIR:-$HOME/.config/zellij}"
