[tools]
amazon-ecr-credential-helper = "latest"
awscli = "latest"
bat = "latest"
chezmoi = "latest"
copilot = "latest"
claude = "latest"
eksctl = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
git-worktree-wrapper = "latest"
github-cli = "latest"
go = "latest"
granted = "latest"
jq = "latest"
kind = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
minikube = "latest"
localstack = "latest"
mkcert = "latest"
neovim = "latest"
node = "latest"
pre-commit = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
task = "latest"
usage = "latest"
uv = "latest"
zellij = "latest"
