---
name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shell:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ludeeus/action-shellcheck@master

      - name: Install shfmt
        run: |
          curl -sSL https://github.com/mvdan/sh/releases/latest/download/shfmt_$(curl -sSL https://api.github.com/repos/mvdan/sh/releases/latest | grep tag_name | cut -d '"' -f4)_linux_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: shfmt
        run: shfmt -d .

  chezmoi:
    name: Chezmoi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin

      - name: Dry run
        run: chezmoi init --apply --dry-run --source .

  lua:
    name: Lua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

      - name: Install luacheck
        run: sudo apt-get install -y luarocks && sudo luarocks install luacheck

      - name: luacheck
        run: luacheck .

  toml:
    name: TOML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz | gunzip > /usr/local/bin/taplo
          chmod +x /usr/local/bin/taplo

      - name: taplo fmt check
        run: taplo fmt --check

  docker:
    name: Docker Bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t dotfiles-test .

      - name: Run
        run: docker run dotfiles-test
